apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 5001  # Updated port to match Dockerfile
      targetPort: 5001
  type: ClusterIP
