apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels: 
        app: container1
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/kubernetes-assignment-454116/kubernetes-assignment-repo/container1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000  # Change this to match the Dockerfile
          volumeMounts:
            - mountPath: "/ekta_PV_dir"
              name: my-storage
      volumes:
        - name: my-storage
          persistentVolumeClaim:
            claimName: ekta-pvc
